"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-tqi34pummn35_i!*bk=i5#z+$)@8@qc0%f@!6as08xzu#%^$h0')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# Em produção, informe o domínio público com https (ex.: https://*.koyeb.app).
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

if not DEBUG:
    # A hospedagem termina o HTTPS num proxy e repassa a requisição em HTTP com este cabeçalho.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # apps do projeto
    'core',
    'usuarios',
    'chamados',
    'ativos',
    'midia',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.ForcarTrocaSenhaMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = config('DATABASE_URL', default=None)
if DATABASE_URL:
    # Usado em produção: connection string do Postgres hospedado (ex.: Neon, com ?sslmode=require).
    import dj_database_url

    DATABASES = {
        # conn_health_checks: bancos serverless (Neon) fecham conexões ociosas; testa antes de reusar.
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600, conn_health_checks=True)
    }
else:
    # Desenvolvimento local: PostgreSQL configurado pelas variáveis DB_* do .env.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default='tcc_chamados'),
            'USER': config('DB_USER', default='postgres'),
            'PASSWORD': config('DB_PASSWORD', default='postgres'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }

AUTH_USER_MODEL = 'usuarios.Usuario'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Uploads (imagens e anexos — app `midia`). Os metadados ficam no Postgres; o arquivo fica:
# - num object storage compatível com S3 (Cloudflare R2, AWS S3, Supabase Storage) quando
#   STORAGE_BUCKET estiver definido — servido direto pela URL pública do bucket, sem passar
#   pelo Django (continua acessível mesmo com o servidor desligado);
# - senão, na pasta local `uploads/` (desenvolvimento), servida pelo Django em DEBUG.
STORAGE_BUCKET = config('STORAGE_BUCKET', default='')

if STORAGE_BUCKET:
    ARMAZENAMENTO_ARQUIVOS = {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            'bucket_name': STORAGE_BUCKET,
            'endpoint_url': config('STORAGE_ENDPOINT_URL', default=None),  # R2/Supabase; vazio = AWS
            'access_key': config('STORAGE_ACCESS_KEY_ID'),
            'secret_key': config('STORAGE_SECRET_ACCESS_KEY'),
            'region_name': config('STORAGE_REGION', default='auto'),
            # Domínio público do bucket (ex.: pub-xxxx.r2.dev): gera URLs permanentes, sem assinatura.
            'custom_domain': config('STORAGE_PUBLIC_DOMAIN', default=None),
            'querystring_auth': False,
            'default_acl': None,  # R2 não usa ACL; a leitura pública é configurada no próprio bucket
            'file_overwrite': False,
            # Chaves são UUIDs e nunca mudam de conteúdo: o navegador pode guardar em cache por 1 ano.
            'object_parameters': {'CacheControl': 'public, max-age=31536000, immutable'},
        },
    }
else:
    ARMAZENAMENTO_ARQUIVOS = {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
        'OPTIONS': {'location': BASE_DIR / 'uploads', 'base_url': '/uploads/'},
    }

STORAGES = {
    'default': ARMAZENAMENTO_ARQUIVOS,
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

LOGIN_URL = 'usuarios:login'
LOGIN_REDIRECT_URL = 'core:dashboard'
LOGOUT_REDIRECT_URL = 'usuarios:login'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
