# Generated by Django 5.2.17 on 2026-09-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_seed_catalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10),
        ),
    ]
