# Generated by Django 5.2.17 on 2026-09-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0005_set_prioridades_catalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='procedimento',
            field=models.TextField(blank=True, help_text='Visível para o solicitante.', verbose_name='Procedimento realizado'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='procedimento_interno',
            field=models.TextField(blank=True, help_text='Visível apenas para a equipe técnica.', verbose_name='Nota interna'),
        ),
    ]
