# Generated by Django 5.2.17 on 2026-09-23 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0006_chamado_procedimento_chamado_procedimento_interno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def migrar_procedimentos_existentes(apps, schema_editor):
        Chamado = apps.get_model('chamados', 'Chamado')
        ProcedimentoEntry = apps.get_model('chamados', 'ProcedimentoEntry')
        for chamado in Chamado.objects.all():
            autor = chamado.atendente_id or chamado.solicitante_id
            if chamado.procedimento:
                ProcedimentoEntry.objects.create(
                    chamado=chamado, autor_id=autor, tipo='publico', texto=chamado.procedimento,
                )
            if chamado.procedimento_interno:
                ProcedimentoEntry.objects.create(
                    chamado=chamado, autor_id=autor, tipo='interno', texto=chamado.procedimento_interno,
                )

    operations = [
        migrations.CreateModel(
            name='ProcedimentoEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('publico', 'Procedimento'), ('interno', 'Nota interna')], default='publico', max_length=10)),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='chamados.chamado')),
            ],
            options={
                'verbose_name': 'Entrada de procedimento',
                'verbose_name_plural': 'Entradas de procedimento',
                'ordering': ['criado_em'],
            },
        ),
        migrations.RunPython(migrar_procedimentos_existentes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='chamado',
            name='procedimento',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='procedimento_interno',
        ),
    ]
