# Generated by Django 5.2.17 on 2026-09-23 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0008_anexo'),
        ('usuarios', '0003_setor_usuario_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='setor',
            field=models.ForeignKey(blank=True, help_text='Setor padrão é o de lotação do solicitante, mas pode ser alterado.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='usuarios.setor'),
        ),
    ]
