# Generated by Django 5.2.17 on 2026-09-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0009_chamado_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPrioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10, unique=True)),
                ('horas', models.PositiveIntegerField(help_text='Prazo, em horas, para resolver um chamado dessa prioridade.')),
            ],
            options={
                'verbose_name': 'SLA por prioridade',
                'verbose_name_plural': 'SLAs por prioridade',
                'ordering': ['prioridade'],
            },
        ),
    ]
