# Generated by Django 5.2.17 on 2026-10-08 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0011_seed_sla'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='sla_pausado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='sla_tempo_pausado',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='procedimentoentry',
            name='tipo',
            field=models.CharField(choices=[('publico', 'Procedimento'), ('interno', 'Nota interna'), ('resposta', 'Resposta do solicitante')], default='publico', max_length=10),
        ),
    ]
