# Generated by Django 5.2.17 on 2026-10-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0012_sla_pausa_resposta_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='resposta_solicitante_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
