# Generated by Django 5.2.17 on 2026-09-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('patrimonio', models.CharField(max_length=50, unique=True, verbose_name='Nº de patrimônio')),
                ('localizacao', models.CharField(blank=True, max_length=150)),
                ('situacao', models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Em manutenção'), ('inativo', 'Inativo')], default='ativo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
