# Generated by Django 5.2.17 on 2026-09-25 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0001_initial'),
        ('chamados', '0011_seed_sla'),
        ('usuarios', '0007_usuario_vip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ativo',
            options={'ordering': ['marca', 'modelo']},
        ),
        migrations.RemoveField(
            model_name='ativo',
            name='localizacao',
        ),
        migrations.RemoveField(
            model_name='ativo',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='ativo',
            name='situacao',
        ),
        migrations.AddField(
            model_name='ativo',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ativos_atribuidos', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído a'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='marca',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ativo',
            name='modelo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ativo',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ativos_lotados', to='usuarios.setor', verbose_name='Setor de lotação'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='status',
            field=models.CharField(choices=[('em_uso', 'Em uso'), ('disponivel', 'Disponível'), ('danificado', 'Danificado'), ('triagem', 'Triagem')], default='disponivel', max_length=20),
        ),
        migrations.AddField(
            model_name='ativo',
            name='tipo',
            field=models.CharField(choices=[('notebook', 'Notebook'), ('desktop', 'Desktop'), ('monitor', 'Monitor'), ('celular', 'Celular'), ('impressora', 'Impressora'), ('outro', 'Outro')], default='outro', max_length=20),
        ),
        migrations.CreateModel(
            name='MovimentacaoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='ativos.ativo')),
                ('chamado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_ativo', to='chamados.chamado')),
                ('funcionario_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('funcionario_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_realizadas', to=settings.AUTH_USER_MODEL)),
                ('setor_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='usuarios.setor')),
                ('setor_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='usuarios.setor')),
            ],
            options={
                'verbose_name': 'Movimentação de ativo',
                'verbose_name_plural': 'Movimentações de ativo',
                'ordering': ['-criado_em'],
            },
        ),
    ]
