# Generated by Django 5.2.17 on 2026-09-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0002_restructure_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoativo',
            name='efetivada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoativo',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('efetivada', 'Efetivada')], default='pendente', max_length=20),
        ),
    ]
