# Generated by Django 5.2.17 on 2026-10-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0003_movimentacaoativo_efetivada_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='patrimonio',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Nº de patrimônio'),
        ),
    ]
