# Generated by Django 5.2.17 on 2026-10-07 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0004_patrimonio_automatico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoativo',
            name='ativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='ativos.ativo'),
        ),
    ]
