# Generated by Django 5.2.17 on 2026-09-23 00:43

from django.db import migrations, models


def gerar_matriculas_existentes(apps, schema_editor):
    Usuario = apps.get_model('usuarios', 'Usuario')
    proxima = 100001
    for usuario in Usuario.objects.order_by('date_joined', 'id'):
        usuario.matricula = str(proxima)
        usuario.save(update_fields=['matricula'])
        proxima += 1


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_setor_usuario_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, default='', editable=False, max_length=20),
            preserve_default=False,
        ),
        migrations.RunPython(gerar_matriculas_existentes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
