# Generated by Django 5.2.17 on 2026-09-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='deve_trocar_senha',
            field=models.BooleanField(default=False, verbose_name='Deve trocar a senha no próximo login'),
        ),
    ]
