# Generated by Django 5.2.17 on 2026-09-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_deve_trocar_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('atendente', 'Técnico'), ('solicitante', 'Solicitante')], default='solicitante', max_length=20),
        ),
    ]
