# Generated by Django 5.2.17 on 2026-09-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='vip',
            field=models.BooleanField(default=False, help_text='Chamados abertos por um solicitante VIP têm o prazo de SLA reduzido em 25%.', verbose_name='Solicitante VIP'),
        ),
    ]
