# Generated by Django 5.2.17 on 2026-09-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='super_admin',
            field=models.BooleanField(default=False, help_text='Acima do administrador comum: tem todas as permissões de administrador, mas nenhum usuário (nem outro admin) pode editá-lo, resetar sua senha ou desativá-lo. Não aparece na listagem de usuários. Só pode ser concedido pelo Django admin.', verbose_name='Superadministrador'),
        ),
    ]
